CREATE DABATASE FILMOTECA;
USE FILMOTECA;

CREATE TABLE PARTICIPANTES(
  CODIGO VARCHAR(255) NOT NULL PRIMARY KEY,
  NOMBRE VARCHAR(255) NOT NULL,
  NACIONALIDAD VARCHAR(100),
  F_NACIMIENTO DATE,
  OSCAR INT,
  NOMINACIONES INT,
  TIPO_PRODUCTO VARCHAR(100)
);

CREATE TABLE SOPORTE(
  CODS BIGINT NOT NULL PRIMARY KEY,
  DESCRIPCION TEXT
);

/*
  PELICULAS
  * CONSTRAINT FK_PELICULAS_PARTICIPANTE
    Llave foranea que hace referencia a la relacion con PARTICIPANTES
  * CONSTRAINT FK_PELICULAS_SOPORTE
    Llave foranea que hace referencia a la relacion con SOPORTE
*/
CREATE TABLE PELICULAS(
  NUM_PEL BIGINT NOT NULL PRIMARY KEY,
  T_ORIGINAL VARCHAR(255) NOT NULL,
  T_TRADUCIDO VARCHAR(255) NOT NULL,
  ANIO_EDICION CHAR(4),
  CATEGORIA VARCHAR(100),
  DURACION TIME,
  PRESUPUESTO FLOAT,
  CALIFICACION FLOAT,
  GUIONISTA VARCHAR(255) NOT NULL,
  SOPORTE BIGINT NOT NULL,
  CONSTRAINT FK_PELICULAS_PARTICIPANTE FOREIGN KEY(GUIONISTA) REFERENCES PARTICIPANTES(CODIGO),
  CONSTRAINT FK_PELICULAS_SOPORTE FOREIGN KEY(SOPORTE) REFERENCES SOPORTE(CODS)
);

/*
  CONSTRAINT CK_PELICULAS_CALIFICACION
  La CALIFICACION no sera menor a 0 y debe ser mayor a 10
*/
ALTER TABLE PELICULAS ADD CONSTRAINT CK_PELICULAS_CALIFICACION CHECK(0 <= CALIFICACION <= 10);

/*
  PROTAGONIZA
  * CONSTRAINT PK_PROTAGONISTA
    Llave primaria compuesta por INTERPRETE y NPEL
  * CONSTRAINT FK_PROTAGONIZA_PARTICIPANTE
    Llave foranea que hace referencia a la relacion con PARTICIPANTES
  * CONSTRAINT FK_PROTAGONIZA_PELICULA
    Llave foranea que hace referencia a la relacion con PELICULAS
*/
CREATE TABLE PROTAGONIZA(
  INTERPRETE VARCHAR(255) NOT NULL,
  NPEL BIGINT NOT NULL,
  TIPO_ACTUACION VARCHAR(255),
  CONSTRAINT PK_PROTAGONISTA PRIMARY KEY(INTERPRETE, NPEL)
  CONSTRAINT FK_PROTAGONIZA_PARTICIPANTE FOREIGN KEY(INTERPRETE) REFERENCES PARTICIPANTES(CODIGO),
  CONSTRAINT FK_PROTAGONIZA_PELICULA FOREIGN KEY(NPEL) REFERENCES PELICULAS(NUM_PEL)
);

/*
  DIRIGE
  * CONSTRAINT PK_DIRIGE
    Llave primaria compuesta por DIRECTOR y NPEL
*/
CREATE TABLE DIRIGE(
  DIRECTOR VARCHAR(255) NOT NULL,
  NPEL BIGINT NOT NULL,
  CONSTRAINT PK_DIRIGE PRIMARY KEY(DIRECTOR, NPEL)
);

/*
  SOCIOS
  CONSTRAINT CK_SOCIO_EDAD revisa que el socio sea mayor o igual a 13 años
*/
CREATE TABLE SOCIOS(
  DNI VARCHAR(100) NOT NULL PRIMARY KEY,
  APELLIDOS VARCHAR(255) NOT NULL,
  NOMBRE VARCHAR(100) NOT NULL,
  DIRECCION VARCHAR(255),
  EDAD INT,
  CONSTRAINT CK_SOCIO_EDAD CHECK (EDAD >= 13)
);

/*
  PRODUCE
  * CONSTRAINT PK_PRODUCE
    Llave primaria compuesta por PRODUCTOR y NPEL
  * CONSTRAINT FK_PRODUCE_PARTICIPANTE
    Llave foranea que hace referencia a la relacion con PARTICIPANTES
  * CONSTRAINT FK_PRODUCE_PELICULA
    Llave foranea que hace referencia a la relacion con PELICULAS
*/
CREATE TABLE PRODUCE(
  PRODUCTOR VARCHAR(255) NOT NULL,
  NPEL BIGINT NOT NULL,
  PORCENTAJE FLOAT,
  CONSTRAINT PK_PRODUCE PRIMARY KEY(PRODUCTOR, NPEL),
  CONSTRAINT FK_PRODUCE_PARTICIPANTE FOREIGN KEY(PRODUCTOR) REFERENCES PARTICIPANTES(CODIGO),
  CONSTRAINT FK_PRODUCE_PELICULA FOREIGN KEY(NPEL) REFERENCES PELICULAS(NUM_PEL)
);

/*
  CICLOS
  * CONSTRAINT PK_CICLOS
    Llave primaria compuesta por NOMBRE y ANIO
*/
CREATE TABLE CICLOS(
  NOMBRE VARCHAR(255) NOT NULL,
  ANIO INT NOT NULL,
  F_INICIO DATE,
  F_FIN DATE,
  CONSTRAINT PK_CICLOS PRIMARY KEY(NOMBRE, ANIO)
);

/*
  CONSTRAINT CK_CICLOS_FECHAS
  La F_FIN no puede ser menor a F_INICIO
*/
ALTER TABLE CICLOS ADD CONSTRAINT CK_CICLOS_FECHAS CHECK(F_FIN > F_INICIO);

/*
  ABONOS
  * CONSTRAINT FK_ABONOS_CICLOS_NOMBRE
    Llave foranea que hace referencia a la relacion con CICLOS
  * CONSTRAINT FK_ABONOS_CICLOS_ANIO
    Llave foranea que hace referencia a la relacion con CICLOS
*/
CREATE TABLE ABONOS(
  COD_A VARCHAR(100) NOT NULL PRIMARY KEY,
  DESCRIPCION TEXT NOT NULL,
  N_DIAS INT,
  COSTO FLOAT,
  CICLO VARCHAR(255) NOT NULL,
  ANIO INT NOT NULL,
  CONSTRAINT FK_ABONOS_CICLOS_NOMBRE FOREIGN KEY(CICLO) REFERENCES CICLOS(NOMBRE),
  CONSTRAINT FK_ABONOS_CICLOS_ANIO FOREIGN KEY(ANIO) REFERENCES CICLOS(ANIO)
);

/*
  CONSTRAINT CK_ABONOS_CICLO_NOMBRE
  El CICLO a insertar en la tabla ABONOS debe coincidir con
  los registrados en la tabla CICLOS
*/
ALTER TABLE ABONOS ADD CONSTRAINT CK_ABONOS_CICLO_NOMBRE
  CHECK(CICLO IN (SELECT NOMBRE FROM CICLOS));

/*
  ALQUILA_P
  * CONSTRAINT FK_ALQUILA_P_PELICULA
    Llave foranea que hace referencia a la relacion con PELICULAS
  * CONSTRAINT FK_ALQUILA_P_SOCIO
    Llave foranea que hace referencia a la relacion con SOCIOS
*/
CREATE TABLE ALQUILA_P(
  NUM_PEL BIGINT NOT NULL,
  SOCIO VARCHAR(100) NOT NULL,
  CONSTRAINT FK_ALQUILA_P_PELICULA FOREIGN KEY(NUM_PEL) REFERENCES PELICULAS(NUM_PEL),
  CONSTRAINT FK_ALQUILA_P_SOCIO FOREIGN KEY(SOCIO) REFERENCES SOCIO(DNI)
);

/*
  BANDAS
  * CONSTRAINT FK_BANDAS_PELICULAS
    Llave foranea que hace referencia a la relacion con PELICULAS
  * CONSTRAINT FK_BANDAS_SOPORTE
    Llave foranea que hace referencia a la relacion con SOPORTE
*/
CREATE TABLE BANDAS(
  CODS_BS VARCHAR(255) NOT NULL PRIMARY KEY,
  TITULO VARCHAR(255) NOT NULL,
  TIPO VARCHAR(100),
  PELICULAS BIGINT NOT NULL,
  SOPORTE BIGINT NOT NULL,
  CONSTRAINT FK_BANDAS_PELICULAS FOREIGN KEY(PELICULAS) REFERENCES PELICULAS(NUM_PEL),
  CONSTRAINT FK_BANDAS_SOPORTE FOREIGN KEY(SOPORTE) REFERENCES SOPORTE(CODS)
);

/*
  ADQUIERE
  * CONSTRAINT FK_ALQUILA_B_BANDA
    Llave foranea que hace referencia a la relacion con BANDAS
  * CONSTRAINT FK_ALQUILA_ABONO
    Llave foranea que hace referencia a la relacion con ABONOS
*/
CREATE TABLE ADQUIERE(
  SOCIO VARCHAR(100) NOT NULL,
  ABONO VARCHAR(100) NOT NULL,
  CONSTRAINT FK_ADQUIERE_SOCIO FOREIGN KEY(SOCIO) REFERENCES SOCIO(DNI),
  CONSTRAINT FK_ADQUIERE_ABONO FOREIGN KEY(ABONO) REFERENCES ABONOS(COD_A)
);

/*
  ALQUILA_B
  * CONSTRAINT FK_ALQUILA_B_BANDAS
    Llave foranea que hace referencia a la relacion con BANDAS
  * CONSTRAINT FK_ALQUILA_B_SOCIO
    Llave foranea que hace referencia a la relacion con SOCIOS
*/
CREATE TABLE ALQUILA_B(
  B_SONORA VARCHAR(255) NOT NULL,
  SOCIO VARCHAR(100) NOT NULL,
  CONSTRAINT FK_ALQUILA_B_BANDA FOREIGN KEY(B_SONORA) REFERENCES BANDAS(CODS_BS),
  CONSTRAINT FK_ALQUILA_B_SOCIO FOREIGN KEY(SOCIO) REFERENCES SOCIO(DNI)
);

/*
  EMITE
  * CONSTRAINT FK_EMITE_PELICULA
    Llave foranea que hace referencia a la relacion con PELICULAS
  * CONSTRAINT FK_EMITE_CICLO_NOMBRE
    Llave foranea que hace referencia a la relacion con CICLOS
  * CONSTRAINT FK_EMITE_CICLO_ANIO
    Llave foranea que hace referencia a la relacion con CICLOS
*/
CREATE TABLE EMITE(
  PELICULA BIGINT NOT NULL,
  CICLO VARCHAR(255) NOT NULL,
  ANIO INT NOT NULL,
  DIA INT,
  HORA TIMESTAMP,
  CONSTRAINT FK_EMITE_PELICULA FOREIGN KEY(PELICULA) REFERENCES PELICULAS(NUM_PEL),
  CONSTRAINT FK_EMITE_CICLO_NOMBRE FOREIGN KEY(CICLO) REFERENCES CICLOS(NOMBRE),
  CONSTRAINT FK_EMITE_CICLO_ANIO FOREIGN KEY(ANIO) REFERENCES CICLOS(ANIO)
);
