USE master;

/*
  Crear los LOGIN de ambos tipos de usuarios
*/
CREATE LOGIN ADMIN_FILMOTECA WITH PASSWORD = '123';
CREATE LOGIN CLIENTE_FILMOTECA WITH PASSWORD = '123';

/*
  Crear USUARIO y asignar al LOGIN creado
*/
USE FILMOTECA;
CREATE USER ADMIN_FILMOTECA FOR LOGIN ADMIN_FILMOTECA;
CREATE USER CLIENTE_FILMOTECA FOR LOGIN CLIENTE_FILMOTECA;

/*
  Otorgar permisos
*/

GRANT SELECT ON SCHEMA::PELICULAS TO CLIENTE_FILMOTECA;
DENY INSERT, DELETE ON SCHEMA::PELICULAS TO CLIENTE_FILMOTECA;
