USE FILMOTECA;
GO

/*
  INDICE NO AGRUPADO en la tabla PELICULAS
*/
CREATE NONCLUSTERED INDEX IN_PELICULAS ON PELICULAS(NUM_PEL);
GO

/*
  Eliminar el INDICE de llave primaria que se encuentre en la tabla PELICULAS
*/
DROP INDEX PK__PELICULA__D5E3D09E07020F21 ON PELICULAS;
GO
