/*
  *** NOTA: se debe activar la autenticacion con inicio de sesion
  con Windows y SQL Server
*/

/*
  Crear para USUARIO ADMIN_FILMOTECA
*/
USE master
GO
CREATE LOGIN ADMIN_FILMOTECA WITH PASSWORD=N'123', DEFAULT_DATABASE=FILMOTECA, CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE FILMOTECA
GO
CREATE USER ADMIN_FILMOTECA FOR LOGIN ADMIN_FILMOTECA
GO
USE FILMOTECA
GO
EXEC sp_addrolemember N'db_accessadmin', N'ADMIN_FILMOTECA'
GO
USE FILMOTECA
GO
EXEC sp_addrolemember N'db_datareader', N'ADMIN_FILMOTECA'
GO
USE FILMOTECA
GO
EXEC sp_addrolemember N'db_datawriter', N'ADMIN_FILMOTECA'
GO
USE FILMOTECA
GO
EXEC sp_addrolemember N'db_owner', N'ADMIN_FILMOTECA'
GO

-- PERMISOS
USE FILMOTECA
GO
GRANT ALTER ON [dbo].[VW_TOTAL_ABONOS_SOCIOS] TO [ADMIN_FILMOTECA]
GO
GRANT INSERT ON [dbo].[VW_TOTAL_ABONOS_SOCIOS] TO [ADMIN_FILMOTECA]
GO
GRANT SELECT ON [dbo].[VW_TOTAL_ABONOS_SOCIOS] TO [ADMIN_FILMOTECA]
GO
GRANT UPDATE ON [dbo].[VW_TOTAL_ABONOS_SOCIOS] TO [ADMIN_FILMOTECA]
GO
GRANT ALTER ON [dbo].[VW_PELICULAS] TO [ADMIN_FILMOTECA]
GO
GRANT INSERT ON [dbo].[VW_PELICULAS] TO [ADMIN_FILMOTECA]
GO
GRANT SELECT ON [dbo].[VW_PELICULAS] TO [ADMIN_FILMOTECA]
GO
GRANT UPDATE ON [dbo].[VW_PELICULAS] TO [ADMIN_FILMOTECA]
GO
GRANT DELETE ON [dbo].[ALQUILA_B] TO [ADMIN_FILMOTECA]
GO
GRANT INSERT ON [dbo].[ALQUILA_B] TO [ADMIN_FILMOTECA]
GO
GRANT SELECT ON [dbo].[ALQUILA_B] TO [ADMIN_FILMOTECA]
GO
GRANT UPDATE ON [dbo].[ALQUILA_B] TO [ADMIN_FILMOTECA]
GO
GRANT DELETE ON [dbo].[ABONOS] TO [ADMIN_FILMOTECA]
GO
GRANT INSERT ON [dbo].[ABONOS] TO [ADMIN_FILMOTECA]
GO
GRANT SELECT ON [dbo].[ABONOS] TO [ADMIN_FILMOTECA]
GO
GRANT UPDATE ON [dbo].[ABONOS] TO [ADMIN_FILMOTECA]
GO
GRANT DELETE ON [dbo].[PARTICIPANTES] TO [ADMIN_FILMOTECA]
GO
GRANT INSERT ON [dbo].[PARTICIPANTES] TO [ADMIN_FILMOTECA]
GO
GRANT SELECT ON [dbo].[PARTICIPANTES] TO [ADMIN_FILMOTECA]
GO
GRANT UPDATE ON [dbo].[PARTICIPANTES] TO [ADMIN_FILMOTECA]
GO
GRANT DELETE ON [dbo].[EMITE] TO [ADMIN_FILMOTECA]
GO
GRANT INSERT ON [dbo].[EMITE] TO [ADMIN_FILMOTECA]
GO
GRANT SELECT ON [dbo].[EMITE] TO [ADMIN_FILMOTECA]
GO
GRANT UPDATE ON [dbo].[EMITE] TO [ADMIN_FILMOTECA]
GO
GRANT DELETE ON [dbo].[SOPORTE] TO [ADMIN_FILMOTECA]
GO
GRANT INSERT ON [dbo].[SOPORTE] TO [ADMIN_FILMOTECA]
GO
GRANT SELECT ON [dbo].[SOPORTE] TO [ADMIN_FILMOTECA]
GO
GRANT UPDATE ON [dbo].[SOPORTE] TO [ADMIN_FILMOTECA]
GO
GRANT EXECUTE ON [dbo].[SP_DELETE_PELICULA] TO [ADMIN_FILMOTECA]
GO
GRANT DELETE ON [dbo].[ALQUILA_P] TO [ADMIN_FILMOTECA]
GO
GRANT INSERT ON [dbo].[ALQUILA_P] TO [ADMIN_FILMOTECA]
GO
GRANT SELECT ON [dbo].[ALQUILA_P] TO [ADMIN_FILMOTECA]
GO
GRANT UPDATE ON [dbo].[ALQUILA_P] TO [ADMIN_FILMOTECA]
GO
GRANT ALTER ON [dbo].[VW_PELICULAS_ALQUILADAS] TO [ADMIN_FILMOTECA]
GO
GRANT INSERT ON [dbo].[VW_PELICULAS_ALQUILADAS] TO [ADMIN_FILMOTECA]
GO
GRANT SELECT ON [dbo].[VW_PELICULAS_ALQUILADAS] TO [ADMIN_FILMOTECA]
GO
GRANT UPDATE ON [dbo].[VW_PELICULAS_ALQUILADAS] TO [ADMIN_FILMOTECA]
GO
GRANT EXECUTE ON [dbo].[SP_INSERT_ALQUILA_P] TO [ADMIN_FILMOTECA]
GO
GRANT DELETE ON [dbo].[DIRIGE] TO [ADMIN_FILMOTECA]
GO
GRANT INSERT ON [dbo].[DIRIGE] TO [ADMIN_FILMOTECA]
GO
GRANT SELECT ON [dbo].[DIRIGE] TO [ADMIN_FILMOTECA]
GO
GRANT UPDATE ON [dbo].[DIRIGE] TO ADMIN_FILMOTECA
GO
GRANT ALTER ON [dbo].[VW_ABONOS_ADQUIRIDOS_POR_SOCIOS] TO [ADMIN_FILMOTECA]
GO
GRANT INSERT ON [dbo].[VW_ABONOS_ADQUIRIDOS_POR_SOCIOS] TO [ADMIN_FILMOTECA]
GO
GRANT SELECT ON [dbo].[VW_ABONOS_ADQUIRIDOS_POR_SOCIOS] TO [ADMIN_FILMOTECA]
GO
GRANT UPDATE ON [dbo].[VW_ABONOS_ADQUIRIDOS_POR_SOCIOS] TO [ADMIN_FILMOTECA]
GO
GRANT EXECUTE ON [dbo].[SP_INSERT_PELICULA] TO [ADMIN_FILMOTECA]
GO
GRANT EXECUTE ON [dbo].[SP_MODIFICAR_SOCIO] TO [ADMIN_FILMOTECA]
GO
GRANT DELETE ON [dbo].[SOCIOS] TO [ADMIN_FILMOTECA]
GO
GRANT INSERT ON [dbo].[SOCIOS] TO [ADMIN_FILMOTECA]
GO
GRANT SELECT ON [dbo].[SOCIOS] TO [ADMIN_FILMOTECA]
GO
GRANT UPDATE ON [dbo].[SOCIOS] TO [ADMIN_FILMOTECA]
GO
GRANT EXECUTE ON [dbo].[SP_INSERT_ALQUILA_B] TO [ADMIN_FILMOTECA]
GO
GRANT DELETE ON [dbo].[ADQUIERE] TO [ADMIN_FILMOTECA]
GO
GRANT INSERT ON [dbo].[ADQUIERE] TO [ADMIN_FILMOTECA]
GO
GRANT SELECT ON [dbo].[ADQUIERE] TO [ADMIN_FILMOTECA]
GO
GRANT UPDATE ON [dbo].[ADQUIERE] TO [ADMIN_FILMOTECA]
GO
GRANT DELETE ON [dbo].[BANDAS] TO [ADMIN_FILMOTECA]
GO
GRANT INSERT ON [dbo].[BANDAS] TO [ADMIN_FILMOTECA]
GO
GRANT SELECT ON [dbo].[BANDAS] TO [ADMIN_FILMOTECA]
GO
GRANT UPDATE ON [dbo].[BANDAS] TO [ADMIN_FILMOTECA]
GO
GRANT DELETE ON [dbo].[PROTAGONIZA] TO [ADMIN_FILMOTECA]
GO
GRANT INSERT ON [dbo].[PROTAGONIZA] TO [ADMIN_FILMOTECA]
GO
GRANT SELECT ON [dbo].[PROTAGONIZA] TO [ADMIN_FILMOTECA]
GO
GRANT UPDATE ON [dbo].[PROTAGONIZA] TO [ADMIN_FILMOTECA]
GO
GRANT EXECUTE ON [dbo].[SP_UPDATE_PELICULA] TO [ADMIN_FILMOTECA]
GO
GRANT EXECUTE ON [dbo].[SP_ADQUIRIR_ABONOS] TO [ADMIN_FILMOTECA]
GO
GRANT DELETE ON [dbo].[CICLOS] TO [ADMIN_FILMOTECA]
GO
GRANT INSERT ON [dbo].[CICLOS] TO [ADMIN_FILMOTECA]
GO
GRANT SELECT ON [dbo].[CICLOS] TO [ADMIN_FILMOTECA]
GO
GRANT UPDATE ON [dbo].[CICLOS] TO [ADMIN_FILMOTECA]
GO
GRANT DELETE ON [dbo].[PRODUCE] TO [ADMIN_FILMOTECA]
GO
GRANT INSERT ON [dbo].[PRODUCE] TO [ADMIN_FILMOTECA]
GO
GRANT SELECT ON [dbo].[PRODUCE] TO [ADMIN_FILMOTECA]
GO
GRANT UPDATE ON [dbo].[PRODUCE] TO [ADMIN_FILMOTECA]
GO
GRANT DELETE ON [dbo].[PELICULAS] TO [ADMIN_FILMOTECA]
GO
GRANT INSERT ON [dbo].[PELICULAS] TO [ADMIN_FILMOTECA]
GO
GRANT SELECT ON [dbo].[PELICULAS] TO [ADMIN_FILMOTECA]
GO
GRANT UPDATE ON [dbo].[PELICULAS] TO ADMIN_FILMOTECA
GO


/*
  Crear USUARIO CLIENTE_FILMOTECA
*/
USE [master]
GO
CREATE LOGIN [CLIENTE_FILMOTECA] WITH PASSWORD=N'123', DEFAULT_DATABASE=[FILMOTECA], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [FILMOTECA]
GO
CREATE USER [CLIENTE_FILMOTECA] FOR LOGIN [CLIENTE_FILMOTECA]
GO
USE [FILMOTECA]
GO
EXEC sp_addrolemember N'db_datareader', N'CLIENTE_FILMOTECA'
GO
USE [FILMOTECA]
GO
EXEC sp_addrolemember N'db_datawriter', N'CLIENTE_FILMOTECA'
GO

-- PERMISOS
use FILMOTECA
GO
GRANT ALTER ON [dbo].[SP_MODIFICAR_SOCIO] TO [CLIENTE_FILMOTECA]
GO
GRANT CONTROL ON [dbo].[SP_MODIFICAR_SOCIO] TO [CLIENTE_FILMOTECA]
GO
GRANT SELECT ON [dbo].[BANDAS] TO [CLIENTE_FILMOTECA]
GO
DENY ALTER ON [dbo].[BANDAS] TO [CLIENTE_FILMOTECA]
GO
DENY DELETE ON [dbo].[BANDAS] TO [CLIENTE_FILMOTECA]
GO
DENY INSERT ON [dbo].[BANDAS] TO [CLIENTE_FILMOTECA]
GO
DENY UPDATE ON [dbo].[BANDAS] TO [CLIENTE_FILMOTECA]
GO
GRANT SELECT ON [dbo].[PELICULAS] TO [CLIENTE_FILMOTECA]
GO
DENY ALTER ON [dbo].[PELICULAS] TO [CLIENTE_FILMOTECA]
GO
DENY DELETE ON [dbo].[PELICULAS] TO [CLIENTE_FILMOTECA]
GO
DENY INSERT ON [dbo].[PELICULAS] TO [CLIENTE_FILMOTECA]
GO
DENY UPDATE ON [dbo].[PELICULAS] TO [CLIENTE_FILMOTECA]
GO
GRANT SELECT ON [dbo].[VW_PELICULAS] TO [CLIENTE_FILMOTECA]
GO
