USE FILMOTECA;
GO

/*
  Crear USUARIO Y ESQUEMA de autorizacion
*/
-- ADMIN_FILMOTECA
EXEC sp_addlogin N'ADMIN_FILMOTECA', 'ADMIN_FILMOTECA'
GO
CREATE USER [ADMIN_FILMOTECA] FOR LOGIN [ADMIN_FILMOTECA]
GO
CREATE SCHEMA [ADMIN_FILMOTECA] AUTHORIZATION db_owner
GO
ALTER USER [ADMIN_FILMOTECA] WITH DEFAULT_SCHEMA=[ADMIN_FILMOTECA]
GO

-- CLIENTE_FILMOTECA
EXEC sp_addlogin N'CLIENTE_FILMOTECA2', 'CLIENTE_FILMOTECA2'
GO
CREATE USER [CLIENTE_FILMOTECA2] FOR LOGIN [CLIENTE_FILMOTECA2]
GO
CREATE SCHEMA [CLIENTE_FILMOTECA2] AUTHORIZATION db_datareader
GO
ALTER USER [CLIENTE_FILMOTECA2] WITH DEFAULT_SCHEMA=[CLIENTE_FILMOTECA2]
GO

/*
  Otorgar PERMISOS
*/
GRANT CREATE TABLE TO ADMIN_FILMOTECA
GO
GRANT CREATE PROCEDURE TO ADMIN_FILMOTECA
GO
GRANT CREATE VIEW TO ADMIN_FILMOTECA
GO
GRANT ALL PRIVILEGES ON SOCIOS TO ADMIN_FILMOTECA;
GO
GRANT ALL PRIVILEGES ON PELICULAS TO ADMIN_FILMOTECA;
GO
GRANT ALL PRIVILEGES ON ALGUILA_P TO ADMIN_FILMOTECA;
GO
GRANT ALL PRIVILEGES ON ALGUILA_B TO ADMIN_FILMOTECA;
GO
GRANT ALL PRIVILEGES ON CICLOS TO ADMIN_FILMOTECA;
GO
GRANT ALL PRIVILEGES ON BANDAS TO ADMIN_FILMOTECA;
GO
GRANT ALL PRIVILEGES ON ABONOS TO ADMIN_FILMOTECA;
GO
GRANT ALL PRIVILEGES ON ADQUIERE TO ADMIN_FILMOTECA;
GO
GRANT ALL PRIVILEGES ON EMITE TO ADMIN_FILMOTECA;
GO
GRANT ALL PRIVILEGES ON DIRIGE TO ADMIN_FILMOTECA;
GO
GRANT ALL PRIVILEGES ON SOPORTE TO ADMIN_FILMOTECA;
GO
GRANT ALL PRIVILEGES ON PRODUCE TO ADMIN_FILMOTECA;
GO
GRANT ALL PRIVILEGES ON PROTAGONIZA TO ADMIN_FILMOTECA;
GO
GRANT ALL PRIVILEGES ON PARTICIPANTES TO ADMIN_FILMOTECA;
GO
GRANT ALL PRIVILEGES ON PELICULAS TO CLIENTE_FILMOTECA2;
GO
DENY INSERT, DELETE, UPDATE ON PELICULAS TO CLIENTE_FILMOTECA2;
GO


/*
  Comprobar PERMISOS de USUARIO
*/
SELECT dp.NAME AS principal_name,
  dp.type_desc AS principal_type_desc,
  o.NAME AS object_name,
  p.permission_name,
  p.state_desc AS permission_state_desc 
  FROM sys.database_permissions p
  LEFT OUTER JOIN sys.all_objects o
  ON p.major_id = o.OBJECT_ID
  INNER JOIN sys.database_principals dp
  ON p.grantee_principal_id = dp.principal_id
  WHERE dp.NAME = 'ADMIN_FILMOTECA2' OR dp.NAME = 'CLIENTE_FILMOTECA2'
GO
